"""Build one non-destructive ZombieSeasons asset-validation gallery batch.

Run this script from Unreal Editor after generating the standard-Python review plan:

py "C:/Users/malik/Documents/Unreal Projects/ZombieSeasons/Content/Python/build_asset_validation_gallery.py"

Each invocation creates only the next missing validation map. Source Fab/Epic assets
are never modified and existing validation maps are never overwritten.
"""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path
from typing import Any

import unreal


PROJECT_ROOT = Path(
    unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
).resolve()
WORLD_MAP_DIRECTORY = PROJECT_ROOT / "Documentation" / "WorldMap"
REVIEW_DIRECTORY = WORLD_MAP_DIRECTORY / "GeneratedAssetReview"
REVIEW_CSV = REVIEW_DIRECTORY / "asset_review.csv"
BATCHES_JSON = REVIEW_DIRECTORY / "batches.json"

DEFAULT_GALLERY_ROOT = "/Game/ZombieSeasons/Validation/AssetGallery"
ENGINE_PLANE = "/Engine/BasicShapes/Plane.Plane"

BATCHES_PER_RUN = 1
MESH_GRID_COLUMNS = 6
MATERIAL_SPACING_CM = 1600.0

# Fixed center spacing is intentional for visual review. Some marketplace meshes
# report oversized bounds because of pivots/helper geometry, which previously spread
# small props over an unnecessarily huge validation map.
CATEGORY_CENTER_SPACING_CM = {
    "barrier_fence": 650.0,
    "street_prop": 700.0,
    "debris_rubble": 900.0,
    "ruin_general": 1800.0,
    "vehicle": 1100.0,
    "stairs_traversal": 1800.0,
    "door_window": 1700.0,
    "roof": 2400.0,
    "structural": 2200.0,
    "wall_facade": 3000.0,
    "architecture_general": 3500.0,
}
DEFAULT_CENTER_SPACING_CM = 1600.0


def log(message: str) -> None:
    unreal.log(f"[ZSAssetGallery] {message}")


def warn(message: str) -> None:
    unreal.log_warning(f"[ZSAssetGallery] {message}")


def fail(message: str) -> None:
    unreal.log_error(f"[ZSAssetGallery] {message}")
    raise RuntimeError(message)


def read_review_rows() -> dict[str, dict[str, str]]:
    """Load the committed review manifest without touching Unreal assets."""
    if not REVIEW_CSV.is_file():
        fail(
            "Review manifest not found. Run "
            "Documentation/WorldMap/Tools/build_asset_review_plan.py first."
        )

    with REVIEW_CSV.open("r", encoding="utf-8-sig", newline="") as stream:
        reader = csv.DictReader(stream)
        required = {
            "review_id",
            "kind",
            "category",
            "pack",
            "review_state",
            "asset_name",
            "asset_class",
            "object_path",
        }
        missing = required - set(reader.fieldnames or ())
        if missing:
            fail("Review CSV is missing columns: " + ", ".join(sorted(missing)))
        rows = {row["review_id"]: dict(row) for row in reader}

    if not rows:
        fail("Review CSV contains no rows.")
    return rows


def read_batches() -> tuple[str, list[dict[str, Any]]]:
    """Read deterministic gallery batches generated by standard Python."""
    if not BATCHES_JSON.is_file():
        fail(
            "Batch plan not found. Run "
            "Documentation/WorldMap/Tools/build_asset_review_plan.py first."
        )

    with BATCHES_JSON.open("r", encoding="utf-8") as stream:
        payload = json.load(stream)

    gallery_root = str(payload.get("gallery_root") or DEFAULT_GALLERY_ROOT)
    batches = payload.get("batches")
    if not isinstance(batches, list) or not batches:
        fail("Batch plan contains no validation batches.")
    return gallery_root, batches


def editor_asset_exists(asset_path: str) -> bool:
    return bool(unreal.EditorAssetLibrary.does_asset_exist(asset_path))


def ensure_directory(asset_path: str) -> None:
    if unreal.EditorAssetLibrary.does_directory_exist(asset_path):
        return
    if not unreal.EditorAssetLibrary.make_directory(asset_path):
        fail(f"Unable to create Unreal content directory: {asset_path}")


def get_level_subsystem() -> Any:
    return unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)


def get_actor_subsystem() -> Any:
    return unreal.get_editor_subsystem(unreal.EditorActorSubsystem)


def create_new_level(asset_path: str) -> None:
    """Create a brand-new map and refuse to overwrite existing validation data."""
    if editor_asset_exists(asset_path):
        fail(f"Refusing to overwrite existing validation map: {asset_path}")

    subsystem = get_level_subsystem()
    success = subsystem.new_level(asset_path)
    if success:
        return

    fallback = getattr(unreal, "EditorLevelLibrary", None)
    if fallback is None or not fallback.new_level(asset_path):
        fail(f"Unable to create validation map: {asset_path}")


def save_current_level() -> None:
    subsystem = get_level_subsystem()
    if subsystem.save_current_level():
        return

    fallback = getattr(unreal, "EditorLevelLibrary", None)
    if fallback is None or not fallback.save_current_level():
        fail("Unable to save the current validation map.")


def spawn_actor(actor_class: Any, location: unreal.Vector, rotation: unreal.Rotator) -> Any:
    subsystem = get_actor_subsystem()
    actor = subsystem.spawn_actor_from_class(actor_class, location, rotation)
    if actor is not None:
        return actor

    fallback = getattr(unreal, "EditorLevelLibrary", None)
    if fallback is None:
        fail(f"Unable to spawn actor class: {actor_class}")

    actor = fallback.spawn_actor_from_class(actor_class, location, rotation)
    if actor is None:
        fail(f"Unable to spawn actor class: {actor_class}")
    return actor


def set_actor_metadata(actor: Any, label: str, folder: str, tags: list[str]) -> None:
    """Give every preview actor deterministic identifiers for human review."""
    try:
        actor.set_actor_label(label, mark_dirty=True)
    except TypeError:
        actor.set_actor_label(label)

    try:
        actor.set_folder_path(unreal.Name(folder))
    except Exception as error:
        warn(f"Unable to set actor folder for {label}: {error}")

    try:
        actor.set_editor_property("tags", [unreal.Name(tag) for tag in tags])
    except Exception as error:
        warn(f"Unable to set tags for {label}: {error}")


def set_static_mesh(actor: Any, mesh: Any) -> Any:
    component = actor.get_editor_property("static_mesh_component")
    if component is None:
        fail(f"StaticMeshActor has no static mesh component: {actor}")
    if not component.set_static_mesh(mesh):
        fail(f"Unable to assign StaticMesh {mesh} to {actor}")
    return component


def set_skeletal_mesh(actor: Any, mesh: Any) -> Any:
    component = actor.get_editor_property("skeletal_mesh_component")
    if component is None:
        fail(f"SkeletalMeshActor has no skeletal mesh component: {actor}")

    for method_name in ("set_skeletal_mesh_asset", "set_skeletal_mesh"):
        method = getattr(component, method_name, None)
        if method is None:
            continue
        method(mesh)
        return component

    fail(f"UE Python exposes no skeletal-mesh setter for {actor}")


def asset_bottom_offset(asset: Any) -> float:
    """Return a best-effort Z offset that places the asset on the preview ground."""
    try:
        bounds = asset.get_bounds()
        origin = bounds.origin
        extent = bounds.box_extent
        value = float(extent.z) - float(origin.z)
        if math.isfinite(value):
            return max(0.0, value)
    except Exception:
        pass
    return 0.0


def load_batch_assets(
    batch: dict[str, Any],
    review_rows: dict[str, dict[str, str]],
) -> list[tuple[dict[str, str], Any]]:
    """Resolve every asset before creating the map so failures are non-destructive."""
    loaded: list[tuple[dict[str, str], Any]] = []

    for review_id in batch["review_ids"]:
        row = review_rows.get(str(review_id))
        if row is None:
            fail(f"Batch references unknown review ID: {review_id}")

        object_path = row["object_path"]
        asset = unreal.load_asset(object_path)
        if asset is None:
            fail(f"Unable to load review asset {review_id}: {object_path}")
        loaded.append((row, asset))

    return loaded


def add_preview_lighting(batch_id: str) -> None:
    """Add one neutral directional light without project-map dependencies."""
    folder = f"ZS_Validation/{batch_id}/Lighting"
    key = spawn_actor(
        unreal.DirectionalLight,
        unreal.Vector(0.0, 0.0, 8000.0),
        unreal.Rotator(-45.0, -35.0, 0.0),
    )
    set_actor_metadata(key, "ZS_Validation_KeyLight", folder, ["ZS_Validation"])
    try:
        component = key.get_component_by_class(unreal.DirectionalLightComponent)
        if component is not None:
            component.set_editor_property("intensity", 5.0)
    except Exception as error:
        warn(f"Unable to configure key light intensity: {error}")


def build_fixed_mesh_layout(
    category: str,
    loaded_assets: list[tuple[dict[str, str], Any]],
) -> tuple[list[tuple[dict[str, str], Any, unreal.Vector]], float, float]:
    """Place preview meshes in a tight deterministic grid at their original scale."""
    if not loaded_assets:
        return [], 4000.0, 4000.0

    spacing = CATEGORY_CENTER_SPACING_CM.get(category, DEFAULT_CENTER_SPACING_CM)
    columns = min(
        MESH_GRID_COLUMNS,
        max(1, math.ceil(math.sqrt(len(loaded_assets)))),
    )
    row_count = math.ceil(len(loaded_assets) / columns)

    placements: list[tuple[dict[str, str], Any, unreal.Vector]] = []
    for index, (row_data, asset) in enumerate(loaded_assets):
        column = index % columns
        grid_row = index // columns
        placements.append(
            (
                row_data,
                asset,
                unreal.Vector(
                    float(column) * spacing,
                    float(grid_row) * spacing,
                    asset_bottom_offset(asset),
                ),
            )
        )

    width_cm = max(4000.0, (columns - 1) * spacing + spacing)
    depth_cm = max(4000.0, (row_count - 1) * spacing + spacing)
    return placements, width_cm, depth_cm


def add_ground_for_bounds(batch_id: str, width_cm: float, depth_cm: float) -> None:
    """Place one neutral plane sized to the compact review grid."""
    plane_mesh = unreal.load_asset(ENGINE_PLANE)
    if plane_mesh is None:
        warn(f"Engine preview plane unavailable: {ENGINE_PLANE}")
        return

    padding = 500.0
    actor = spawn_actor(
        unreal.StaticMeshActor,
        unreal.Vector(
            (width_cm - padding) * 0.5,
            (depth_cm - padding) * 0.5,
            -2.0,
        ),
        unreal.Rotator(0.0, 0.0, 0.0),
    )
    set_static_mesh(actor, plane_mesh)
    actor.set_actor_scale3d(
        unreal.Vector(
            (width_cm + padding * 2.0) / 100.0,
            (depth_cm + padding * 2.0) / 100.0,
            1.0,
        )
    )
    set_actor_metadata(
        actor,
        "ZS_Validation_Ground",
        f"ZS_Validation/{batch_id}/Environment",
        ["ZS_Validation", "ZS_Validation_Ground"],
    )


def build_mesh_batch(
    batch: dict[str, Any],
    loaded_assets: list[tuple[dict[str, str], Any]],
) -> None:
    category = str(batch["category"])
    batch_id = str(batch["batch_id"])
    folder = f"ZS_Validation/{batch_id}/Assets"

    placements, width_cm, depth_cm = build_fixed_mesh_layout(category, loaded_assets)
    add_ground_for_bounds(batch_id, width_cm, depth_cm)

    for row, asset, location in placements:
        if row["asset_class"] == "StaticMesh":
            actor = spawn_actor(
                unreal.StaticMeshActor,
                location,
                unreal.Rotator(0.0, 0.0, 0.0),
            )
            set_static_mesh(actor, asset)
        elif row["asset_class"] == "SkeletalMesh":
            actor = spawn_actor(
                unreal.SkeletalMeshActor,
                location,
                unreal.Rotator(0.0, 0.0, 0.0),
            )
            set_skeletal_mesh(actor, asset)
        else:
            fail(
                f"Unsupported mesh class {row['asset_class']} for "
                f"{row['review_id']}"
            )

        label = f"{row['review_id']}__{row['asset_name']}"
        set_actor_metadata(
            actor,
            label,
            folder,
            [
                "ZS_Validation",
                f"ZS_ReviewId_{row['review_id']}",
                f"ZS_Category_{category}",
                f"ZS_Pack_{row['pack']}",
            ],
        )


def build_material_batch(
    batch: dict[str, Any],
    loaded_assets: list[tuple[dict[str, str], Any]],
) -> None:
    """Preview AsphaltMat variants on large engine planes."""
    batch_id = str(batch["batch_id"])
    folder = f"ZS_Validation/{batch_id}/Materials"
    plane_mesh = unreal.load_asset(ENGINE_PLANE)
    if plane_mesh is None:
        fail(f"Engine preview plane unavailable: {ENGINE_PLANE}")

    columns = 5
    for index, (row, material) in enumerate(loaded_assets):
        column = index % columns
        grid_row = index // columns
        actor = spawn_actor(
            unreal.StaticMeshActor,
            unreal.Vector(
                float(column) * MATERIAL_SPACING_CM,
                float(grid_row) * MATERIAL_SPACING_CM,
                0.0,
            ),
            unreal.Rotator(0.0, 0.0, 0.0),
        )
        component = set_static_mesh(actor, plane_mesh)
        component.set_material(0, material)
        actor.set_actor_scale3d(unreal.Vector(12.0, 12.0, 1.0))

        label = f"{row['review_id']}__{row['asset_name']}"
        set_actor_metadata(
            actor,
            label,
            folder,
            [
                "ZS_Validation",
                f"ZS_ReviewId_{row['review_id']}",
                "ZS_Category_road_material",
                "ZS_Pack_AsphaltMat",
            ],
        )


def build_batch(
    gallery_root: str,
    batch: dict[str, Any],
    review_rows: dict[str, dict[str, str]],
) -> str:
    """Create one batch map after all referenced source assets load successfully."""
    batch_id = str(batch["batch_id"])
    map_name = str(batch["map_name"])
    map_path = f"{gallery_root}/{map_name}"

    loaded_assets = load_batch_assets(batch, review_rows)
    create_new_level(map_path)
    add_preview_lighting(batch_id)

    kind = str(batch["kind"])
    if kind == "MESH":
        build_mesh_batch(batch, loaded_assets)
    elif kind == "MATERIAL":
        build_material_batch(batch, loaded_assets)
    else:
        fail(f"Unsupported validation batch kind: {kind}")

    save_current_level()
    log(
        f"Created {map_path} with {len(loaded_assets)} review assets "
        f"({batch['category']})."
    )
    return map_path


def collect_garbage_if_available() -> None:
    """Best-effort cleanup between future multi-batch modes."""
    try:
        method = getattr(unreal.SystemLibrary, "collect_garbage", None)
        if method is not None:
            method()
    except Exception as error:
        warn(f"Garbage collection request failed: {error}")


def run() -> None:
    review_rows = read_review_rows()
    gallery_root, batches = read_batches()
    ensure_directory(gallery_root)

    pending = [
        batch
        for batch in batches
        if not editor_asset_exists(f"{gallery_root}/{batch['map_name']}")
    ]

    if not pending:
        message = (
            "All asset-validation gallery maps already exist.\n\n"
            f"Gallery root:\n{gallery_root}"
        )
        log(message.replace("\n", " "))
        unreal.EditorDialog.show_message(
            "ZombieSeasons Asset Validation",
            message,
            unreal.AppMsgType.OK,
        )
        return

    created: list[str] = []
    for batch in pending[:BATCHES_PER_RUN]:
        created.append(build_batch(gallery_root, batch, review_rows))
        collect_garbage_if_available()

    remaining = len(pending) - len(created)
    message = (
        f"Created validation batch:\n{created[-1]}\n\n"
        f"Remaining batches: {remaining}\n\n"
        "Inspect the actors by their M#### / A### labels in the Outliner.\n"
        "Run the same Python command again to build the next batch."
    )
    unreal.EditorDialog.show_message(
        "ZombieSeasons Asset Validation",
        message,
        unreal.AppMsgType.OK,
    )


if __name__ == "__main__":
    run()
